# Numpy - Libaray to handle arrays. 
- statically typed (element types can't be mixed or altered)
- non resizeable (can't append or remove elements)
- much faster than pythons dynamically typed lists.
- support use of vector operations.


In [7]:
import numpy as np

my_array = np.array([5 , 2, 6, 8])

print(my_array)

[5 2 6 8]


## Create arrays


In [5]:
a2 = np.random.random(20) * 100
a2

a3 = np.random.randint(10, 20, 5)
a3

array([19, 13, 17, 18, 15])

a4 = np.zeros(10)

In [7]:
a4 = np.zeros(10)
a4

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
a6 = np.linspace(0, 10, 15)
a7 = np.arange(0, 10, 0.3)
a7

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8, 2.1, 2.4, 2.7, 3. , 3.3, 3.6,
       3.9, 4.2, 4.5, 4.8, 5.1, 5.4, 5.7, 6. , 6.3, 6.6, 6.9, 7.2, 7.5,
       7.8, 8.1, 8.4, 8.7, 9. , 9.3, 9.6, 9.9])

# vectorized operations


In [1]:
x = [2, 5, 4, 1, 8, 6, 4, 3]
x

[2, 5, 4, 1, 8, 6, 4, 3]

In [3]:
new_x = [y + 2 for y in x]
new_x

[4, 7, 6, 3, 10, 8, 6, 5]

In [8]:
r = np.array([2, 1, 3, 4, 5, 2, 1, 4])

In [9]:
r * 2 + 1 

array([ 5,  3,  7,  9, 11,  5,  3,  9])

In [12]:
a = np.array([5, 2, 1, 4])
b = np.array([2, 1, 3, 4])

np.sqrt(a**2 + b**2)

array([5.38516481, 2.23606798, 3.16227766, 5.65685425])